In [89]:
import torch

input = torch.tensor([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]]).float()
input
input.shape

torch.Size([1, 1, 3, 3])

In [46]:
from torch.nn import ConvTranspose2d

conv_transpose = ConvTranspose2d(in_channels=1, out_channels=1,
                                 kernel_size=3,   # カーネルサイズを決めるとconv2dにおけるpaddingの幅が決まる（kernel_size -1 のはばの余白が取られる）
                                 stride=2,  # conv2dにおけるstrideと同じだが、inputの要素を無視しないように各行と各列に余白を追加する
                                 padding=0,  # 削る余白
                                 output_padding=0,  # 出力に付け足す余白
                                 dilation=1,  # カーネルを拡大させるパラメータ（カーネル要素の間隔を空ける(膨張畳み込み)、デフォルトは拡大しない(=1)）
                                 )

# 重みとバイアスを単純な値で初期化
# ここでは重みをすべて1に設定し、バイアスを0に設定
conv_transpose.weight.data.fill_(1)
conv_transpose.bias.data.fill_(0)

output = conv_transpose(input)
output

tensor([[[[ 1.,  1.,  3.,  2.,  5.,  3.,  3.],
          [ 1.,  1.,  3.,  2.,  5.,  3.,  3.],
          [ 5.,  5., 12.,  7., 16.,  9.,  9.],
          [ 4.,  4.,  9.,  5., 11.,  6.,  6.],
          [11., 11., 24., 13., 28., 15., 15.],
          [ 7.,  7., 15.,  8., 17.,  9.,  9.],
          [ 7.,  7., 15.,  8., 17.,  9.,  9.]]]],
       grad_fn=<ConvolutionBackward0>)

In [53]:
in_h = 16
# outが32となるようにパラメータを設定する

kernel_size = 3
stride = 2
padding = 1
dilation = 1
output_padding = 1

out = (in_h - 1) * stride - 2 * padding + dilation * (kernel_size - 1) + output_padding + 1
out  # -> 32

32

In [65]:
in_h = 16
# outが32となるようにパラメータを設定する

kernel_size = 3
stride = 2
padding = 1
dilation = 2
output_padding = -1

out = (in_h - 1) * stride - 2 * padding + dilation * (kernel_size - 1) + output_padding + 1
out  # -> 32

32

In [79]:
in_h = 6

# outが2倍になるようにパラメータ（一般的な例）
kernel_size = 3
stride = 1

padding = 0  # デフォルト値、outputから削る余白の幅（余白は削らない）
output_padding = 0  # デフォルト値（出力に付け足す余白はない）
dilation = 1  # デフォルト値（カーネルは拡大しない）

# 出力サイズ計算式
out = (in_h - 1) * stride - 2 * padding + dilation * (kernel_size - 1) + output_padding + 1
out

8

In [86]:
input2 = input.detach().clone()
input2

tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]])

In [88]:
cat = torch.cat([input, input2], dim=1)
cat

tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]],

         [[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]])